# Generated by Django 5.2.1 on 2025-05-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
