# Generated by Django 5.2.1 on 2025-05-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
